[project]
name = "book-lauch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=4.2,<5.0",
    "openpyxl>=3.1.0",
    "psycopg2-binary>=2.9.11",
    "python-decouple>=3.8",
]
